name: cielo
version: '0.1.2.0'
author: Pedro Tacla Yamada
synopsis: Cielo API v3 Bindings for Haskell
description: Cielo API v3 Bindings
maintainer: tacla.yamada@gmail.com
category: Web
license: AllRightsReserved
homepage: https://github.com/beijaflor-io/haskell-cielo

extra-source-files:
- ChangeLog.md

default-extensions:
- OverloadedStrings
- TemplateHaskell
- ConstraintKinds
- FlexibleContexts
- RecordWildCards
- ScopedTypeVariables

dependencies:
- base >=4.8 && <5
- text >=1.2 && <1.3
- template-haskell >=2.11 && <2.12
- aeson
- mtl
- uuid >=1.3 && <1.4
- wreq
- lens
- convertible
- bytestring
- http-types
- http-client >=0.4.31.1
- data-default

library:
  source-dirs: src
  exposed-modules:
  - Web.Payments.Cielo
  - Web.Payments.Cielo.Types
  - Web.Payments.Cielo.Types.DeriveJSON

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - hspec
    - QuickCheck
    - cielo
    - pretty-show
